apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-app
  namespace: argocd
spec:
  project: default
  source:
    # repoURL: https://github.com/ayoubabounakif/Inception-of-Things
    repoURL: https://gitlab.com/ayoubabounakif/inception-of-things-k3d-agent-setup.git
    targetRevision: HEAD
    # targetRevision: confs
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
