apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  labels:
    name: hello-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: app1
    http:
      paths:
      - pathType: Prefix
        path: "/app1"
        backend:
          service:
            name: hello-one
            port:
              number: 80