apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-app
  labels:
    app: will-app
  namespace: argocd
spec:
  project: development
  source:
    path: helm
    repoURL: https://github.com/ayoubabounakif/Inception-of-Things
    targetRevision: confs
    helm:
      valueFiles:
        - values.yaml
    # path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true