apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayoubabounakif/aabounak
    targetRevision: confs
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
