apiVersion: apps/v1
kind: Deployment
metadata:
  name: wils-app
  namespace: dev
  labels:
    app: wils-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wils-app
  template:
    metadata:
      labels:
        app: wils-app
    spec:
      containers:
      - name: app
        image: "wil42/playground:v1"
        ports:
        - containerPort: 8888
